### TEST DRIVER API
GET http://localhost:5000/driver

###
POST http://localhost:5000/driver
Content-Type: application/json

{
  "fname": "Tam",
  "lname": "Tam",
  "phone_number": "123",
  "driving_license": "A7526988"
}

###
DELETE http://localhost:5000/driver/69
