### TEST RIDE API
GET http://localhost:5000/ride

###
GET http://localhost:5000/ride/43

###
POST http://localhost:5000/ride
Content-Type: application/json

{
  "passengerid": 7,
  "driverid": 69,
  "pickup_location": "Tha-it",
  "dropoff_location": "THE MALL",
  "price": 300
}

###
DELETE http://localhost:5000/ride/42

###
PUT http://localhost:5000/ride/1

###
PUT http://localhost:5000/ride/con/28
Content-Type: application/json

{
  "driverid": 70
}